name = "Argon2"
uuid = "d0b8aacb-a1ca-4807-a7a0-0a65b3233cb0"
version = "0.2.0"
authors = ["FYP <fyp1534@gmail.com>"]

[deps]
argon2_jll = "2b4f1e85-fc50-5eed-88c0-58968af4dd78"

[compat]
argon2_jll = "^20190702.1.0"
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
